App/Controllers/Client_Group_MasterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DbAccess;
using Microsoft.AspNet.Identity;
using System.Linq.Dynamic;

namespace App.Controllers
{
    [Authorize(Roles = "Tech_Support")]
    public class Client_Group_MasterController : Controller
    {
        private FACSDBEntities db = new FACSDBEntities();

        // GET: Client_Group_Master
        public ActionResult Index()
        {
            //db.Client_Group_Master.ToList()
            return View();
        }

        public JsonResult GetclientGrpList(DataTableAjaxPostModel model)
        {
            // action inside a standard controller
            int filteredResultsCount;
            int totalResultsCount;

            var subCatLst = db.Client_Group_Master.ToList();

            var GetList = GetClintGrpDatTableLst(subCatLst, model, out filteredResultsCount, out totalResultsCount);

            return Json(new
            {
                data = GetList,
                draw = model.draw,
                recordsTotal = totalResultsCount,
                recordsFiltered = filteredResultsCount,
            }, JsonRequestBehavior.AllowGet);
        }

        private object GetClintGrpDatTableLst(List<Client_Group_Master> lst, DataTableAjaxPostModel model, out int filteredResultsCount, out int totalResultsCount)
        {
            string searchBy = (model.search != null) ? model.search.value : null;
            var take = model.length;
            var skip = model.start;
            var sortBy = "name";
            string sortDir = "ASC";

            totalResultsCount = lst.Count();

            if (model.order != null)
            {
                // in this example we just default sort on the 1st column
                sortBy = model.columns[model.order[0].column].data;
                sortDir = model.order[0].dir.ToLower() == "asc" ? "ASC" : "DESC";
            }
            if (!String.IsNullOrEmpty(searchBy))
            {
                lst = lst.Where(x => x.Hospital_Group_Name.ToLower().Contains(searchBy.ToLower())).ToList();
            }

            filteredResultsCount = lst.Count();
            lst = lst.Skip(skip).Take(take).ToList();

            var lstCityformate = lst.Select(x => new
            {
                id = x.Hospital_Group_Id,
                x.Hospital_Group_Name,
                x.Hospital_Group_Code,
                created_at = x.Create_Dt_Time.ToString("MMM,dd,yyy"),
                updated_at = x.Update_Dt_Time.ToString("MMM,dd,yyy")
            });

            if (lst == null)
            {
                // empty collection...
                return new List<Client_Group_Master>();
            }
            lstCityformate = lstCityformate.OrderBy(sortBy + " " + sortDir).ToList();
            return lstCityformate;
        }

        // GET: Client_Group_Master/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client_Group_Master client_Group_Master = db.Client_Group_Master.Find(id);
            if (client_Group_Master == null)
            {
                return HttpNotFound();
            }
            return View(client_Group_Master);
        }

        // GET: Client_Group_Master/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Client_Group_Master/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Hospital_Group_Name,Hospital_Group_Code,Commission_Percentage")] Client_Group_Master client_Group_Master)
        {
            if (ModelState.IsValid)
            {
                DateTime dt = DateTime.Now;
                client_Group_Master.Created_By_User = User.Identity.GetUserId<int>();
                client_Group_Master.Updated_By_User = User.Identity.GetUserId<int>();
                client_Group_Master.Create_Dt_Time = dt;
                client_Group_Master.Update_Dt_Time = dt;
                db.Client_Group_Master.Add(client_Group_Master);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client_Group_Master);
        }

        // GET: Client_Group_Master/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client_Group_Master client_Group_Master = db.Client_Group_Master.Find(id);
            if (client_Group_Master == null)
            {
                return HttpNotFound();
            }
            return View(client_Group_Master);
        }

        // POST: Client_Group_Master/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Hospital_Group_Id,Hospital_Group_Name,Hospital_Group_Code,Commission_Percentage")] Client_Group_Master client_Group_Master)
        {
            if (ModelState.IsValid)
            {
                Client_Group_Master dbClientGrpMst = db.Client_Group_Master.Find(client_Group_Master.Hospital_Group_Id);
                dbClientGrpMst.Hospital_Group_Name = client_Group_Master.Hospital_Group_Name;
                dbClientGrpMst.Hospital_Group_Code = client_Group_Master.Hospital_Group_Code;
                dbClientGrpMst.Commission_Percentage = client_Group_Master.Commission_Percentage;
                dbClientGrpMst.Updated_By_User = User.Identity.GetUserId<int>();
                dbClientGrpMst.Update_Dt_Time = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client_Group_Master);
        }

        // GET: Client_Group_Master/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client_Group_Master client_Group_Master = db.Client_Group_Master.Find(id);
            if (client_Group_Master == null)
            {
                return HttpNotFound();
            }
            return View(client_Group_Master);
        }

        // POST: Client_Group_Master/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client_Group_Master client_Group_Master = db.Client_Group_Master.Find(id);
            db.Client_Group_Master.Remove(client_Group_Master);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/Patient_StatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DbAccess;
using Microsoft.AspNet.Identity;
using System.Linq.Dynamic;

namespace App.Controllers
{
    [Authorize(Roles = "Tech_Support,SrCollectors,Collectors")]
    public class Patient_StatusController : Controller
    {
        private FACSDBEntities db = new FACSDBEntities();

        // GET: Patient_Status
        public ActionResult Index()
        {
            //var patient_Status = db.Patient_Status.Include(p => p.Disposition_Master).Include(p => p.Patient_Master).Include(p=>p.Contact_Master);
            //return View(patient_Status.ToList());
            return View();
        }

        public JsonResult GetJsonList(DataTableAjaxPostModel model)
        {
            // action inside a standard controller
            int filteredResultsCount;
            int totalResultsCount;

            var jsonLst = db.Patient_Status.Include(p => p.Disposition_Master).Include(p => p.Patient_Master).Include(p => p.Contact_Master).ToList();

            var GetList = GetDatTableLst(jsonLst, model, out filteredResultsCount, out totalResultsCount);

            return Json(new
            {
                data = GetList,
                draw = model.draw,
                recordsTotal = totalResultsCount,
                recordsFiltered = filteredResultsCount,
            }, JsonRequestBehavior.AllowGet);
        }

        private object GetDatTableLst(List<Patient_Status> lst, DataTableAjaxPostModel model, out int filteredResultsCount, out int totalResultsCount)
        {
            string searchBy = (model.search != null) ? model.search.value : null;
            var take = model.length;
            var skip = model.start;
            var sortBy = "socialSecurityNo";
            string sortDir = "ASC";

            totalResultsCount = lst.Count();

            if (model.order != null)
            {
                // in this example we just default sort on the 1st column
                sortBy = model.columns[model.order[0].column].data;
                sortDir = model.order[0].dir.ToLower() == "asc" ? "ASC" : "DESC";
            }
            if (!String.IsNullOrEmpty(searchBy))
            {
                lst = lst.Where(x => x.Patient_Master.Patient_SocialSecurity.ToLower().Contains(searchBy.ToLower())).ToList();
            }

            filteredResultsCount = lst.Count();
            lst = lst.Skip(skip).Take(take).ToList();

            var lstCityformate = lst.Select(x => new
            {
                id = x.Status_Id,
                socialSecurityNo = x.Patient_Master.Patient_SocialSecurity,
                patientNoFrmClient = x.Patient_Master.PatientNoFromClient,
                name = x.Patient_Master.Patient_First_Name + " " + x.Patient_Master.Patient_Middle_Name + " " + x.Patient_Master.Patient_Last_Name,
                Collector = x.Contact_Master.Contact_Person_Name,
                created_at = x.Create_Dt_Time.Value.ToString("MMM,dd,yyy"),
                updated_at = x.Uppdate_Dt_Time.Value.ToString("MMM,dd,yyy")
            });

            if (lst == null)
            {
                // empty collection...
                return new List<Patient_Status>();
            }
            lstCityformate = lstCityformate.OrderBy(sortBy + " " + sortDir).ToList();
            return lstCityformate;
        }

        // GET: Patient_Status/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient_Status patient_Status = db.Patient_Status.Find(id);
            if (patient_Status == null)
            {
                return HttpNotFound();
            }
            return View(patient_Status);
        }

        // GET: Patient_Status/Create
        public ActionResult Create()
        {
            ViewBag.Disposition_Id = new SelectList(db.Disposition_Master, "Disposition_Id", "Disposition");
            ViewBag.Patient_Id = new SelectList(db.Patient_Master, "Patient_Id", "PatientNoFromClient");
            ViewBag.Collector_Id = new SelectList(db.Contact_Master, "Contact_Id", "Contact_Person_Name");
            return View();
        }

        // POST: Patient_Status/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Patient_Id,Collector_Id,Disposition_Id,Contact_Date,Method_Of_Contact,Valid_Contact_Number,Valid_Contact_Number_Type,Current_Balance,Notes,IsLatest,Last_Payment_Date,Last_Payment_Amount,Total_Paid_Amount")] Patient_Status patient_Status)
        {
            if (ModelState.IsValid)
            {
                DateTime dt = DateTime.Now;
                patient_Status.Created_By_User = User.Identity.GetUserId<int>();
                patient_Status.Create_Dt_Time = dt;
                patient_Status.Updated_By_User = User.Identity.GetUserId<int>();
                patient_Status.Uppdate_Dt_Time = dt;

                db.Patient_Status.Add(patient_Status);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Disposition_Id = new SelectList(db.Disposition_Master, "Disposition_Id", "Disposition", patient_Status.Disposition_Id);
            ViewBag.Patient_Id = new SelectList(db.Patient_Master, "Patient_Id", "PatientNoFromClient", patient_Status.Patient_Id);
            ViewBag.Collector_Id = new SelectList(db.Contact_Master, "Contact_Id", "Contact_Person_Name");
            return View(patient_Status);
        }

        // GET: Patient_Status/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient_Status patient_Status = db.Patient_Status.Find(id);
            if (patient_Status == null)
            {
                return HttpNotFound();
            }
            ViewBag.Disposition_Id = new SelectList(db.Disposition_Master, "Disposition_Id", "Disposition", patient_Status.Disposition_Id);
            ViewBag.Patient_Id = new SelectList(db.Patient_Master, "Patient_Id", "PatientNoFromClient", patient_Status.Patient_Id);
            ViewBag.Collector_Id = new SelectList(db.Contact_Master, "Contact_Id", "Contact_Person_Name", patient_Status.Collector_Id);
            return View(patient_Status);
        }

        // POST: Patient_Status/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Status_Id,Patient_Id,Collector_Id,Disposition_Id,Contact_Date,Method_Of_Contact,Valid_Contact_Number,Valid_Contact_Number_Type,Current_Balance,Notes,IsLatest,Last_Payment_Date,Last_Payment_Amount,Total_Paid_Amount")] Patient_Status patient_Status)
        {
            if (ModelState.IsValid)
            {
                DateTime dt = DateTime.Now;
                patient_Status.Updated_By_User = User.Identity.GetUserId<int>();
                patient_Status.Uppdate_Dt_Time = dt;
                var excluded = new[] { "Created_By_User", "Create_Dt_Time" };
                var patientMaster = db.Entry(patient_Status);
                patientMaster.State = EntityState.Modified;
                foreach (var item in excluded)
                {
                    patientMaster.Property(item).IsModified = false;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Disposition_Id = new SelectList(db.Disposition_Master, "Disposition_Id", "Disposition", patient_Status.Disposition_Id);
            ViewBag.Patient_Id = new SelectList(db.Patient_Master, "Patient_Id", "PatientNoFromClient", patient_Status.Patient_Id);
            ViewBag.Collector_Id = new SelectList(db.Contact_Master, "Contact_Id", "Contact_Person_Name", patient_Status.Collector_Id);
            return View(patient_Status);
        }

        // GET: Patient_Status/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient_Status patient_Status = db.Patient_Status.Find(id);
            if (patient_Status == null)
            {
                return HttpNotFound();
            }
            return View(patient_Status);
        }

        // POST: Patient_Status/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Patient_Status patient_Status = db.Patient_Status.Find(id);
            db.Patient_Status.Remove(patient_Status);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Views/Patient_Status/Create.cshtml
@model DbAccess.Patient_Status

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Patient Status</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Patient_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Patient_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Patient_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Collector_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Collector_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Collector_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Disposition_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Disposition_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Disposition_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact_Date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Contact_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Method_Of_Contact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Method_Of_Contact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Method_Of_Contact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valid_Contact_Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valid_Contact_Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valid_Contact_Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valid_Contact_Number_Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valid_Contact_Number_Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valid_Contact_Number_Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Current_Balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Current_Balance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Current_Balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsLatest, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsLatest)
                    @Html.ValidationMessageFor(model => model.IsLatest, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        
        <div class="form-group">
            @Html.LabelFor(model => model.Last_Payment_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Last_Payment_Date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Last_Payment_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Last_Payment_Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Last_Payment_Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Last_Payment_Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total_Paid_Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total_Paid_Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total_Paid_Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section styles {
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/bootstrap-datepicker.min.css")" />
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/moment.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-datepicker.min.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $('.datepicker').datepicker({ autoclose: true });
        });
    </script>
}

App/Views/Patient_Status/Delete.cshtml
@model DbAccess.Patient_Status

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient_Status</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Collector_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Collector_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Method_Of_Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Method_Of_Contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valid_Contact_Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valid_Contact_Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valid_Contact_Number_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valid_Contact_Number_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Current_Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Current_Balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsLatest)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsLatest)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Last_Payment_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Last_Payment_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Last_Payment_Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Last_Payment_Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total_Paid_Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_Paid_Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Disposition_Master.Disposition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Disposition_Master.Disposition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patient_Master.PatientNoFromClient)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient_Master.PatientNoFromClient)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

App/Views/Patient_Status/Index.cshtml
@model IEnumerable<DbAccess.Patient_Status>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, htmlAttributes: new { @class = "btn btn-primary btn-lg" })
</p>
<div>
    <div class="table table-responsive">
        <table id="SpaLst">
            <thead>
                <tr>
                    <th>Social Security No.</th>
                    <th>Patient Number</th>
                    <th>Name</th>
                    <th>Collector</th>
                    <th>Created Date</th>
                    <th>Updated Date</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        var theGrid = null;
        $(document).ready(function () {
            theGrid = $("#SpaLst").DataTable({
                "processing": true,
                "serverSide": true,
                "ordering": true,
                "responsive": false,
                "autoWidth": false,
                "ajax": { "url": '@Url.Action("GetJsonList", "Patient_Status")', "type": "post", "datatype": "json" },
                "columnDefs": [
                    {
                        "targets": 0,
                        "visible": true,
                        "searchable": true,
                        "class": "never"
                    },
                    {
                        "render": function (data, type, row) {
                            return '<a href="@Url.Action("Edit", "Patient_Status")/' + row.id + '">Edit</a> | <a href="@Url.Action("Details", "Patient_Status")/' + row.id + '">Details</a> | <a href="@Url.Action("Delete", "Patient_Status")/' + row.id + '">Delete</a>';
                        },
                        "sortable": false,
                        "targets": 6
                    }
                ],
                "columns": [
                       { "data": "socialSecurityNo", "autoWidth": true },
                       { "data": "patientNoFrmClient", "autoWidth": true },
                       { "data": "name", "autoWidth": true },
                       { "data": "Collector", "autoWidth": true },
                       { "data": "created_at", "autoWidth": true },
                       { "data": "updated_at", "autoWidth": true }
                ]@*,
                dom: 'Blfrtip',
                buttons: [
                    {
                        text: 'Add new',
                        action: function (e, dt, node, config)
                        {
                            //This will send the page to the location specified
                            window.location.href = '@Url.Action("Create", "Client_Group_Master")';
                        },
                        className: 'btn btn-primary btn-lg'
                    }
                ]*@
            });
        });
    </script>
}