App/Controllers/Client_Group_MasterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DbAccess;
using Microsoft.AspNet.Identity;
using System.Linq.Dynamic;

namespace App.Controllers
{
    [Authorize(Roles = "Tech_Support")]
    public class Client_Group_MasterController : Controller
    {
        private FACSDBEntities db = new FACSDBEntities();

        // GET: Client_Group_Master
        public ActionResult Index()
        {
            //db.Client_Group_Master.ToList()
            return View();
        }

        public JsonResult GetclientGrpList(DataTableAjaxPostModel model)
        {
            // action inside a standard controller
            int filteredResultsCount;
            int totalResultsCount;

            var subCatLst = db.Client_Group_Master.ToList();

            var GetList = GetClintGrpDatTableLst(subCatLst, model, out filteredResultsCount, out totalResultsCount);

            return Json(new
            {
                data = GetList,
                draw = model.draw,
                recordsTotal = totalResultsCount,
                recordsFiltered = filteredResultsCount,
            }, JsonRequestBehavior.AllowGet);
        }

        private object GetClintGrpDatTableLst(List<Client_Group_Master> lst, DataTableAjaxPostModel model, out int filteredResultsCount, out int totalResultsCount)
        {
            string searchBy = (model.search != null) ? model.search.value : null;
            var take = model.length;
            var skip = model.start;
            var sortBy = "name";
            string sortDir = "ASC";

            totalResultsCount = lst.Count();

            if (model.order != null)
            {
                // in this example we just default sort on the 1st column
                sortBy = model.columns[model.order[0].column].data;
                sortDir = model.order[0].dir.ToLower() == "asc" ? "ASC" : "DESC";
            }
            if (!String.IsNullOrEmpty(searchBy))
            {
                lst = lst.Where(x => x.Hospital_Group_Name.ToLower().Contains(searchBy.ToLower())).ToList();
            }

            filteredResultsCount = lst.Count();
            lst = lst.Skip(skip).Take(take).ToList();

            var lstCityformate = lst.Select(x => new
            {
                id = x.Hospital_Group_Id,
                x.Hospital_Group_Name,
                x.Hospital_Group_Code,
                created_at = x.Create_Dt_Time.ToString("MMM,dd,yyy"),
                updated_at = x.Update_Dt_Time.ToString("MMM,dd,yyy")
            });

            if (lst == null)
            {
                // empty collection...
                return new List<Client_Group_Master>();
            }
            lstCityformate = lstCityformate.OrderBy(sortBy + " " + sortDir).ToList();
            return lstCityformate;
        }

        // GET: Client_Group_Master/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client_Group_Master client_Group_Master = db.Client_Group_Master.Find(id);
            if (client_Group_Master == null)
            {
                return HttpNotFound();
            }
            return View(client_Group_Master);
        }

        // GET: Client_Group_Master/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Client_Group_Master/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Hospital_Group_Name,Hospital_Group_Code,Commission_Percentage")] Client_Group_Master client_Group_Master)
        {
            if (ModelState.IsValid)
            {
                DateTime dt = DateTime.Now;
                client_Group_Master.Created_By_User = User.Identity.GetUserId<int>();
                client_Group_Master.Updated_By_User = User.Identity.GetUserId<int>();
                client_Group_Master.Create_Dt_Time = dt;
                client_Group_Master.Update_Dt_Time = dt;
                db.Client_Group_Master.Add(client_Group_Master);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client_Group_Master);
        }

        // GET: Client_Group_Master/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client_Group_Master client_Group_Master = db.Client_Group_Master.Find(id);
            if (client_Group_Master == null)
            {
                return HttpNotFound();
            }
            return View(client_Group_Master);
        }

        // POST: Client_Group_Master/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Hospital_Group_Id,Hospital_Group_Name,Hospital_Group_Code,Commission_Percentage")] Client_Group_Master client_Group_Master)
        {
            if (ModelState.IsValid)
            {
                Client_Group_Master dbClientGrpMst = db.Client_Group_Master.Find(client_Group_Master.Hospital_Group_Id);
                dbClientGrpMst.Hospital_Group_Name = client_Group_Master.Hospital_Group_Name;
                dbClientGrpMst.Hospital_Group_Code = client_Group_Master.Hospital_Group_Code;
                dbClientGrpMst.Commission_Percentage = client_Group_Master.Commission_Percentage;
                dbClientGrpMst.Updated_By_User = User.Identity.GetUserId<int>();
                dbClientGrpMst.Update_Dt_Time = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client_Group_Master);
        }

        // GET: Client_Group_Master/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client_Group_Master client_Group_Master = db.Client_Group_Master.Find(id);
            if (client_Group_Master == null)
            {
                return HttpNotFound();
            }
            return View(client_Group_Master);
        }

        // POST: Client_Group_Master/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client_Group_Master client_Group_Master = db.Client_Group_Master.Find(id);
            db.Client_Group_Master.Remove(client_Group_Master);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/Contact_Sub_Type_MasterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DbAccess;
using System.Linq.Dynamic;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    [Authorize(Roles = "Tech_Support")]
    public class Contact_Sub_Type_MasterController : Controller
    {
        private FACSDBEntities db = new FACSDBEntities();

        // GET: Contact_Sub_Type_Master
        public ActionResult Index()
        {
            //var contact_Sub_Type_Master = db.Contact_Sub_Type_Master.Include(c => c.Contact_Type_Master);
            //contact_Sub_Type_Master.ToList();
            return View();
        }

        public JsonResult GetJsonList(DataTableAjaxPostModel model)
        {
            // action inside a standard controller
            int filteredResultsCount;
            int totalResultsCount;

            var jsonLst = db.Contact_Sub_Type_Master.Include(c => c.Contact_Type_Master).ToList();

            var GetList = GetDatTableLst(jsonLst, model, out filteredResultsCount, out totalResultsCount);

            return Json(new
            {
                data = GetList,
                draw = model.draw,
                recordsTotal = totalResultsCount,
                recordsFiltered = filteredResultsCount,
            }, JsonRequestBehavior.AllowGet);
        }

        private object GetDatTableLst(List<Contact_Sub_Type_Master> lst, DataTableAjaxPostModel model, out int filteredResultsCount, out int totalResultsCount)
        {
            string searchBy = (model.search != null) ? model.search.value : null;
            var take = model.length;
            var skip = model.start;
            var sortBy = "Contact_Sub_Type";
            string sortDir = "ASC";

            totalResultsCount = lst.Count();

            if (model.order != null)
            {
                // in this example we just default sort on the 1st column
                sortBy = model.columns[model.order[0].column].data;
                sortDir = model.order[0].dir.ToLower() == "asc" ? "ASC" : "DESC";
            }
            if (!String.IsNullOrEmpty(searchBy))
            {
                lst = lst.Where(x => x.Contact_Sub_Type.ToLower().Contains(searchBy.ToLower())).ToList();
            }

            filteredResultsCount = lst.Count();
            lst = lst.Skip(skip).Take(take).ToList();

            var lstCityformate = lst.Select(x => new
            {
                id = x.Contact_Sub_Type_Id,
                x.Contact_Sub_Type,
                x.Contact_Type_Master.Contact_Type,
                created_at = x.Create_Dt_Time.Value.ToString("MMM,dd,yyy"),
                updated_at = x.Update_Dt_Time.Value.ToString("MMM,dd,yyy")
            });

            if (lst == null)
            {
                // empty collection...
                return new List<Contact_Sub_Type_Master>();
            }
            lstCityformate = lstCityformate.OrderBy(sortBy + " " + sortDir).ToList();
            return lstCityformate;
        }

        // GET: Contact_Sub_Type_Master/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact_Sub_Type_Master contact_Sub_Type_Master = db.Contact_Sub_Type_Master.Find(id);
            if (contact_Sub_Type_Master == null)
            {
                return HttpNotFound();
            }
            return View(contact_Sub_Type_Master);
        }

        // GET: Contact_Sub_Type_Master/Create
        public ActionResult Create()
        {
            ViewBag.Contact_Type_Id = new SelectList(db.Contact_Type_Master, "Contact_Type_Id", "Contact_Type");
            return View();
        }

        // POST: Contact_Sub_Type_Master/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Contact_Type_Id,Contact_Sub_Type")] Contact_Sub_Type_Master contact_Sub_Type_Master)
        {
            if (ModelState.IsValid)
            {
                DateTime dt = DateTime.Now;
                contact_Sub_Type_Master.Created_By_User = User.Identity.GetUserId<int>();
                contact_Sub_Type_Master.Create_Dt_Time = dt;
                contact_Sub_Type_Master.Updated_By_User = User.Identity.GetUserId<int>();
                contact_Sub_Type_Master.Update_Dt_Time = dt;
                db.Contact_Sub_Type_Master.Add(contact_Sub_Type_Master);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Contact_Type_Id = new SelectList(db.Contact_Type_Master, "Contact_Type_Id", "Contact_Type", contact_Sub_Type_Master.Contact_Type_Id);
            return View(contact_Sub_Type_Master);
        }

        // GET: Contact_Sub_Type_Master/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact_Sub_Type_Master contact_Sub_Type_Master = db.Contact_Sub_Type_Master.Find(id);
            if (contact_Sub_Type_Master == null)
            {
                return HttpNotFound();
            }
            ViewBag.Contact_Type_Id = new SelectList(db.Contact_Type_Master, "Contact_Type_Id", "Contact_Type", contact_Sub_Type_Master.Contact_Type_Id);
            return View(contact_Sub_Type_Master);
        }

        // POST: Contact_Sub_Type_Master/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Contact_Sub_Type_Id,Contact_Type_Id,Contact_Sub_Type")] Contact_Sub_Type_Master contact_Sub_Type_Master)
        {
            if (ModelState.IsValid)
            {
                DateTime dt = DateTime.Now;
                Contact_Sub_Type_Master cst = db.Contact_Sub_Type_Master.Find(contact_Sub_Type_Master.Contact_Sub_Type_Id);
                cst.Contact_Type_Id = contact_Sub_Type_Master.Contact_Type_Id;
                cst.Contact_Sub_Type = contact_Sub_Type_Master.Contact_Sub_Type;
                contact_Sub_Type_Master.Updated_By_User = User.Identity.GetUserId<int>();
                contact_Sub_Type_Master.Update_Dt_Time = dt;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Contact_Type_Id = new SelectList(db.Contact_Type_Master, "Contact_Type_Id", "Contact_Type", contact_Sub_Type_Master.Contact_Type_Id);
            return View(contact_Sub_Type_Master);
        }

        // GET: Contact_Sub_Type_Master/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact_Sub_Type_Master contact_Sub_Type_Master = db.Contact_Sub_Type_Master.Find(id);
            if (contact_Sub_Type_Master == null)
            {
                return HttpNotFound();
            }
            return View(contact_Sub_Type_Master);
        }

        // POST: Contact_Sub_Type_Master/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contact_Sub_Type_Master contact_Sub_Type_Master = db.Contact_Sub_Type_Master.Find(id);
            db.Contact_Sub_Type_Master.Remove(contact_Sub_Type_Master);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Views/Contact_Sub_Type_Master/Create.cshtml
@model DbAccess.Contact_Sub_Type_Master

@{
    ViewBag.Title = "Create Contact Sub Type";
}

<h2>Create Contact Sub Type</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Contact Sub Type</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Contact_Sub_Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact_Sub_Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact_Sub_Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact_Type_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Contact_Type_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Contact_Type_Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

App/Views/Contact_Sub_Type_Master/Delete.cshtml
@model DbAccess.Contact_Sub_Type_Master

@{
    ViewBag.Title = "Delete Contact Sub Type";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contact Sub Type</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Contact_Sub_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact_Sub_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact_Type_Master.Contact_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact_Type_Master.Contact_Type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

App/Views/Contact_Sub_Type_Master/Details.cshtml
@model DbAccess.Contact_Sub_Type_Master

@{
    ViewBag.Title = "Details Contact Sub Type";
}

<h2>Details</h2>

<div>
    <h4>Contact Sub Type</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Contact_Sub_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact_Sub_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact_Type_Master.Contact_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact_Type_Master.Contact_Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Create_Dt_Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Create_Dt_Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Update_Dt_Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Update_Dt_Time)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Contact_Sub_Type_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

App/Views/Contact_Sub_Type_Master/Edit.cshtml
@model DbAccess.Contact_Sub_Type_Master

@{
    ViewBag.Title = "Edit Contact Sub Type";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Contact Sub Type</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Contact_Sub_Type_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Contact_Sub_Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact_Sub_Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact_Sub_Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact_Type_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Contact_Type_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Contact_Type_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

App/Views/Contact_Sub_Type_Master/Index.cshtml
@model IEnumerable<DbAccess.Contact_Sub_Type_Master>

@{
    ViewBag.Title = "Index";
}

<h2>Contact Sub Type</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, htmlAttributes: new { @class = "btn btn-primary btn-lg" })
</p>
<div>
    <div class="table table-responsive">
        <table id="SpaLst">
            <thead>
                <tr>
                    <th>Contact Type</th>
                    <th>Contact Sub Type</th>
                    <th>Created Date</th>
                    <th>Updated Date</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        var theGrid = null;
        $(document).ready(function () {
            theGrid = $("#SpaLst").DataTable({
                "processing": true,
                "serverSide": true,
                "ordering": true,
                "responsive": false,
                "autoWidth": false,
                "ajax": { "url": '@Url.Action("GetJsonList", "Contact_Sub_Type_Master")', "type": "post", "datatype": "json" },
                "columnDefs": [
                    {
                        "targets": 0,
                        "visible": true,
                        "searchable": true,
                        "class": "never"
                    },
                    {
                        "render": function (data, type, row) {
                            return '<a href="@Url.Action("Edit", "Contact_Sub_Type_Master")/' + row.id + '">Edit</a> | <a href="@Url.Action("Details", "Contact_Sub_Type_Master")/' + row.id + '">Details</a> | <a href="@Url.Action("Delete", "Contact_Sub_Type_Master")/' + row.id + '">Delete</a>';
                        },
                        "sortable": false,
                        "targets": 4
                    }
                ],
                "columns": [
                       { "data": "Contact_Sub_Type", "autoWidth": true },
                       { "data": "Contact_Type", "autoWidth": true },
                       { "data": "created_at", "autoWidth": true },
                       { "data": "updated_at", "autoWidth": true }
                ]@*,
                dom: 'Blfrtip',
                buttons: [
                    {
                        text: 'Add new',
                        action: function (e, dt, node, config)
                        {
                            //This will send the page to the location specified
                            window.location.href = '@Url.Action("Create", "Client_Group_Master")';
                        },
                        className: 'btn btn-primary btn-lg'
                    }
                ]*@
            });
        });
    </script>
}